version: "3.7"
services:
  app:
    build:
      args:
        user: talentloop
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: brm
    container_name: brm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - brm

  db:
    image: mariadb:10.6
    container_name: brm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DB_PORT}:3307
    volumes:
      - ./docker-compose/database:/docker-entrypoint-initdb.d
    networks:
      - brm

  nginx:
    image: nginx:1.23-alpine
    container_name: brm-nginx
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      #- ./docker-compose/nginx:/etc/php.d/pdo_pgsql.ini
    networks:
      - brm

networks:
  brm:
    driver: bridge